Modifications to make pre-commit hooks safe
Modifications suggested by:
      http://tech.yipit.com/2011/11/16/183772396/
      http://codeinthehole.com/writing/tips-for-using-a-git-pre-commit-hook/#comment-645959940

diff --git a/git-hooks b/git-hooks
--- a/git-hooks
+++ b/git-hooks
@@ -6,13 +6,13 @@
 # Redistribution and use in source and binary forms, with or without
 # modification, are permitted provided that the following conditions are met:
 # 1. Redistributions of source code must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
+#     notice, this list of conditions and the following disclaimer.
 # 2. Redistributions in binary form must reproduce the above copyright
-#    notice, this list of conditions and the following disclaimer in the
-#    documentation and/or other materials provided with the distribution.
+#	 notice, this list of conditions and the following disclaimer in the
+#	 documentation and/or other materials provided with the distribution.
 # 3. Neither the name of the project nor the
-#    names of its contributors may be used to endorse or promote products
-#    derived from this software without specific prior written permission.
+#	 names of its contributors may be used to endorse or promote products
+#	 derived from this software without specific prior written permission.
 #
 # THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDER ''AS IS'' AND ANY
 # EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
@@ -28,147 +28,164 @@
 
 function hook_dirs
 {
-    if [ ! -z "${1}" ] ; then
-        hook="/${1}"
-    else
-        hook=""
-    fi
-    echo "${HOME}/.git_hooks${hook}"
-    GITDIR=`git rev-parse --git-dir`
-    cd $GITDIR/.. > /dev/null
-    echo "${PWD}/git_hooks${hook}"
-    echo "${PWD}/.githooks${hook}"
-    eval echo "`git config hooks.global`"${hook}
+	if [ ! -z "${1}" ] ; then
+		hook="/${1}"
+	else
+		hook=""
+	fi
+	echo "${HOME}/.git_hooks${hook}"
+	GITDIR=`git rev-parse --git-dir`
+	cd $GITDIR/.. > /dev/null
+	echo "${PWD}/git_hooks${hook}"
+	echo "${PWD}/.githooks${hook}"
+	eval echo "`git config hooks.global`"${hook}
 }
 
 function list_hooks_in_dir
 {
-    find -L "${1}/" -perm +111 -type f 2>/dev/null | grep -v "^.$" | sort
+	find -L "${1}/" -perm +111 -type f 2>/dev/null | grep -v "^.$" | sort
 }
 
 function run_hooks
 {
-    dir="${1}"
-    if [[ -z ${dir} || ! -d "${dir}" ]] ; then
-        echo "run_hooks requires a directory name as an argument."
-        return 1
-    fi
-    shift 1
-    for hook in `list_hooks_in_dir "${dir}"`
-    do
-        export last_run_hook="${hook} $@"
-        if [ ! -z ${GIT_HOOKS_VERBOSE} ] ; then
-            echo -n "@@ Running hook: "
-            echo -n `basename \`dirname "${hook}"\``
-            echo "/`basename "${hook}"`"
-        fi
-        ${hook} "$@"
-    done
+	dir="${1}"
+	if [[ -z ${dir} || ! -d "${dir}" ]] ; then
+		echo "run_hooks requires a directory name as an argument."
+		return 1
+	fi
+	shift 1
+	for hook in `list_hooks_in_dir "${dir}"`
+	do
+		export last_run_hook="${hook} $@"
+		if [ ! -z ${GIT_HOOKS_VERBOSE} ] ; then
+			echo -n "@@ Running hook: "
+			echo -n `basename \`dirname "${hook}"\``
+			echo "/`basename "${hook}"`"
+		fi
+		${hook} "$@"
+		ret_code=$?
+		if [ ${ret_code} != 0 ]; then
+			printf "Error : [%d] when executing command: '${hook} $@'\n" ${ret_code}
+			oneerror="yup"
+		fi
+	done
 }
 
 function run_hook
 {
-    set -e
-    hook=`basename "${1}"`
-    if [ -z ${hook} ] ; then
-        echo "run requires a hook argument"
-        return 1
-    fi
-    shift 1
-    for dir in `hook_dirs "${hook}"`; do
-        if [ ! -d "${dir}" ] ; then
-            continue
-        fi
-        run_hooks "${dir}" "$@"
-    done
-    set +e
+	hook=`basename "${1}"`
+	if [ -z ${hook} ] ; then
+		echo "run requires a hook argument"
+		return 1
+	fi
+	if [ "${hook}" == "pre-commit" ]; then
+		git diff-index --quiet HEAD --
+		if [ $? -gt 0 ]; then
+			git stash --quiet --include-untracked --keep-index
+			gottasave="yup"
+		fi
+	fi
+	shift 1
+	for dir in `hook_dirs "${hook}"`; do
+		if [ ! -d "${dir}" ] ; then
+			continue
+		fi
+		run_hooks "${dir}" "$@"
+	done
+	if [ "${gottasave}" == "yup" ]; then
+		git reset --hard --quiet
+		git stash pop --quiet --index
+	fi
+	if [ "${oneerror}" == "yup" ]; then
+		exit 1
+	fi
 }
 
 function install_hooks
 {
-    GITDIR=`git rev-parse --git-dir`
-    if [ ! $? -eq 0 ] ; then
-        echo "$1 must be run inside a git repository"
-        return 1
-    fi
-    cd $GITDIR
-    if [ "${1}" = "--install" ] ; then
-        if [ -d hooks.old ] ; then
-            echo "hooks.old already exists, perhaps you already installed?"
-            return 1
-        fi
-        mv hooks hooks.old
-        mkdir hooks
-        cd hooks
-        for file in applypatch-msg commit-msg post-applypatch post-checkout post-commit post-merge post-receive pre-applypatch pre-auto-gc pre-commit prepare-commit-msg pre-rebase pre-receive update
-        do
-            echo '#!/bin/bash
+	GITDIR=`git rev-parse --git-dir`
+	if [ ! $? -eq 0 ] ; then
+		echo "$1 must be run inside a git repository"
+		return 1
+	fi
+	cd $GITDIR
+	if [ "${1}" = "--install" ] ; then
+		if [ -d hooks.old ] ; then
+			echo "hooks.old already exists, perhaps you already installed?"
+			return 1
+		fi
+		mv hooks hooks.old
+		mkdir hooks
+		cd hooks
+		for file in applypatch-msg commit-msg post-applypatch post-checkout post-commit post-merge post-receive pre-applypatch pre-auto-gc pre-commit prepare-commit-msg pre-rebase pre-receive update
+		do
+			echo '#!/bin/bash
 git-hooks run "$0" "$@"' > "${file}"
-            chmod +x "${file}"
-        done
-    else
-        if [ ! -d hooks.old ] ; then
-            echo "Error, hooks.old doesn't exists, aborting uninstall to not destroy something"
-            return 1
-        fi
-        rm -rf hooks
-        mv hooks.old hooks
-    fi
+			chmod +x "${file}"
+		done
+	else
+		if [ ! -d hooks.old ] ; then
+			echo "Error, hooks.old doesn't exists, aborting uninstall to not destroy something"
+			return 1
+		fi
+		rm -rf hooks
+		mv hooks.old hooks
+	fi
 }
 
 function list_hooks
 {
-    GITDIR=`git rev-parse --git-dir`
-    cat $GITDIR/hooks/pre-commit 2> /dev/null | grep 'git-hooks' > /dev/null 2> /dev/null
-    if [ $? = 0 ] ; then
-        echo "Git hooks ARE installed in this repository."
-        echo ""
-    else
-        echo "Git hooks are NOT installed in this repository."
-        echo ""
-    fi
+	GITDIR=`git rev-parse --git-dir`
+	cat $GITDIR/hooks/pre-commit 2> /dev/null | grep 'git-hooks' > /dev/null 2> /dev/null
+	if [ $? = 0 ] ; then
+		echo "Git hooks ARE installed in this repository."
+		echo ""
+	else
+		echo "Git hooks are NOT installed in this repository."
+		echo ""
+	fi
 
-    echo 'Listing User, Project, and Global hooks:'
-    echo '---'
-    for dir in `hook_dirs`; do
-        echo "${dir}:"
-        for hook in `list_hooks_in_dir "${dir}"` ; do
-            echo -n `basename \`dirname "${hook}"\``
-            echo -e "/`basename "${hook}"` \t- `${hook} --about`"
-        done
-        echo ""
-    done
+	echo 'Listing User, Project, and Global hooks:'
+	echo '---'
+	for dir in `hook_dirs`; do
+		echo "${dir}:"
+		for hook in `list_hooks_in_dir "${dir}"` ; do
+			echo -n `basename \`dirname "${hook}"\``
+			echo -e "/`basename "${hook}"` \t- `${hook} --about`"
+		done
+		echo ""
+	done
 }
 
 function report_error {
-    echo "Hook failed: $last_run_hook"
-    exit 1
+	echo "Hook failed: $last_run_hook"
+	exit 1
 }
 
 case $1 in
-    run )
-        if [ ! -z "${GIT_DIR}" ] ; then
-            unset GIT_DIR
-        fi
-        shift
-        trap report_error ERR
-        run_hook "$@"
-        ;;
-    --install|--uninstall )
-        install_hooks "$1"
-        ;;
-    -h|--help|-? )
-        echo 'Git Hooks'
-        echo ''
-        echo 'Options:'
-        echo '    --install      Replace existing hooks in this repository with a call to'
-        echo '                   git hooks run [hook].  Move old hooks directory to hooks.old'
-        echo '    --uninstall    Remove existing hooks in this repository and rename hooks.old'
-        echo '                   back to hooks'
-        echo "    run [cmd]      Run the hooks for cmd (such as pre-commit)"
-        echo "    (no arguments) Show currently installed hooks"
-        ;;
-    * )
-        list_hooks
-        ;;
+	run )
+		if [ ! -z "${GIT_DIR}" ] ; then
+			unset GIT_DIR
+		fi
+		shift
+		trap report_error ERR
+		run_hook "$@"
+		;;
+	--install|--uninstall )
+		install_hooks "$1"
+		;;
+	-h|--help|-? )
+		echo 'Git Hooks'
+		echo ''
+		echo 'Options:'
+		echo '	  --install		 Replace existing hooks in this repository with a call to'
+		echo '					 git hooks run [hook].	Move old hooks directory to hooks.old'
+		echo '	  --uninstall	 Remove existing hooks in this repository and rename hooks.old'
+		echo '					 back to hooks'
+		echo "	  run [cmd]		 Run the hooks for cmd (such as pre-commit)"
+		echo "	  (no arguments) Show currently installed hooks"
+		;;
+	* )
+		list_hooks
+		;;
 esac
